# More info about this file at https://github.com/terraform-ibm-modules/common-pipeline-assets/blob/main/.github/workflows/terraform-test-pipeline.md#cra-config-yaml
version: "v1"
CRA_TARGETS:
  - CRA_TARGET: "solutions/banking"
    CRA_IGNORE_RULES_FILE: "cra-tf-validate-ignore-rules.json"
    PROFILE_ID: "0e6e7b5a-817d-4344-ab6f-e5d7a9c49520"
    CRA_ENVIRONMENT_VARIABLES:
      TF_VAR_toolchain_region: "us-south"
      TF_VAR_ci_pipeline_id: "4e621b22-5802-4013-896a-777fc345f424"
      TF_VAR_cd_pipeline_id: "4e621b22-5802-4013-896a-777fc345f424"
      TF_VAR_watson_assistant_instance_id: "4e621b22-5802-4013-896a-777fc345f424"
      TF_VAR_watson_assistant_region: "us-south"
      TF_VAR_watson_discovery_instance_id: "4e621b22-5802-4013-896a-777fc345f424"
      TF_VAR_watson_discovery_region: "us-south"
